In [12]:
dt = pd.read_csv('training_data.csv')
dt['id']=dt['id'].fillna(" ")
dt['headline']=dt['headline'].fillna(" ")
dt['written_by']=dt['written_by'].fillna(" ")
dt['news']=dt['news'].fillna(" ")
dt['label']=dt['label'].fillna(" ")
dt.dropna(axis=1)

C:\Users\Lasya Priya D\AppData\Local\Temp\ipykernel_15912\3713283013.py:1: DtypeWarning: Columns (15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541) have mixed types. Specify dtype option on import or set low_memory=False.
  dt = pd.read_csv('training_data.csv')

,id,headline,written_by,news,label
0,9653,Ethics Questions Dogged Agriculture Nominee as...,Eric Lipton and Steve Eder,"WASHINGTON â€” In Sonny Perdueâ€™s telling,...",0
1,10041,U.S. Must Dig Deep to Stop Argentinaâ€™s Lione...,David Waldstein,HOUSTON â€” Venezuela had a plan. It was a ...,0
2,19113,Cotton to House: â€™Do Not Walk the Plank and ...,Pam Key,"Sunday on ABCâ€™s â€œThis Week,â€ while discu...",0
3,6868,"Paul LePage, Besieged Maine Governor, Sends Co...",Jess Bidgood,"AUGUSTA, Me. â€” The beleaguered Republican...",0
4,7596,A Digital 9/11 If Trump Wins,Finian Cunningham,Finian Cunningham has written extensively on...,1
...,...,...,...,...,...
9616,9207,YOUTUBE BANS â€˜CLINTONâ€™S BLACK SONâ€™,Iron Sheik,Home â€º US NEWS â€º YOUTUBE BANS â€˜CLINTONâ€...,1
9617,4444,The Sex Scandal That Could Change The Election,Jason Bermas,We Are Change \nWith only days away from the m...,1
9618,5822,Trump Releases New TV Ad that Uses Anthony Wei...,LN Buzz Team,A candidate under FBI investigation? Check.\nA...,1
9619,12732,"Michael Flynn, Kim Jong-un: Your Tuesday Eveni...",Karen Zraick and Lisa Iaboni,(Want to get this briefing by email? Hereâ€™s ...,0
9620,10871,"From Links to Lucifer to Calls for Execution, ...",Alan Rappeport,There have been aerial signs reading â€œHillar...,

In [22]:
#A1
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
 

df['news']=df['news'].fillna('')
x=df['news']
y=df['label']

train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=50)
merged_x=pd.concat([train_x,test_x],axis=0,ignore_index=True)
vectorize=CountVectorizer()
merged_x_vect=vectorize.fit_transform(merged_x)
df_without_labels=df.drop(columns=['label'])

x_train_vect=vectorize.fit_transform(train_x)
x_test_vect=vectorize.transform(test_x)

k=3
kmeans_cluster=KMeans(n_clusters=k,random_state=50)
kmeans_cluster.fit(merged_x_vect)

df_without_labels['clusters']=kmeans_cluster.labels_

df_without_labels.dropna(axis=1)

C:\Users\Lasya Priya D\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

                                                   news  clusters
0     WASHINGTON  â€”   In Sonny Perdueâ€™s telling,...         0
1     HOUSTON  â€”   Venezuela had a plan. It was a ...         2
2     Sunday on ABCâ€™s â€œThis Week,â€ while discu...         2
3     AUGUSTA, Me.  â€”   The beleaguered Republican...         0
4       Finian Cunningham has written extensively on...         0
...                                                 ...       ...
9616  Home â€º US NEWS â€º YOUTUBE BANS â€˜CLINTONâ€...         0
9617  We Are Change \nWith only days away from the m...         0
9618  A candidate under FBI investigation? Check.\nA...         2
9619  (Want to get this briefing by email? Hereâ€™s ...         2
9620  There have been aerial signs reading â€œHillar...         2

[9621 rows x 2 columns]